### ISSUE TITLE
Typo in formquad input documentation

### ISSUE THREAD

**Issue by Shagun-G** [POptUS/IBCDFO#77]
In the python implementation for pounders model formation code; formquad.py, the documentation for the inputs says "npmax" for maximum number of interpolation points which I believe should be "mpmax." Hope this is correct 🙃.

**Comment by wildsm** [comment]
Thanks for raising this.
I believe in the initial translation we were concerned with confusion between n(um)p(y).max and `npmax`.

`mpmax` only appears in the python versions.

All `mpmax` should be replaced by `npmax`. This should be straightforward, but care needs to be taken since `npmax` appears in a few of the `py/` files, namely

- checkinputss.py
- formquad.py
- tests/regression_tests/test_failing_objective.py
